import type { ReleaseRecord } from './protocol';

export function renderDownloadPage(release: ReleaseRecord, downloadUrl: string): string {
  const size = `${(release.size_bytes / 1024 / 1024).toFixed(1)} MB`;
  const commit = release.commit_sha.slice(0, 12);
  const notes = escapeHtml(release.release_notes || 'Latest stable Private Browser release for Windows.');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Download Private Browser</title><style>
  :root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:#080b11;color:#e8edf7}*{box-sizing:border-box}body{min-height:100vh;margin:0;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 50% 0,#16264a 0,transparent 40%),#080b11}.card{width:min(680px,100%);border:1px solid #283249;border-radius:24px;background:linear-gradient(180deg,#151b28,#0e131d);box-shadow:0 28px 90px #0009;padding:38px}.brand{display:flex;gap:12px;align-items:center;color:#9eb7ff;font-weight:750}.shield{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;background:#557ff522;border:1px solid #6a92ff55}h1{font-size:clamp(30px,6vw,48px);letter-spacing:-.04em;margin:28px 0 10px}p{color:#96a2b7;line-height:1.65}.version{display:inline-flex;padding:6px 10px;border:1px solid #33405b;border-radius:999px;color:#b9c8f5;background:#1a2232;font-size:13px}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:24px 0}.meta div,.checksum{background:#0b1018;border:1px solid #252e40;border-radius:12px;padding:13px}.meta small,.checksum small{display:block;color:#647086;text-transform:uppercase;letter-spacing:.08em;font-size:10px}.meta strong{display:block;margin-top:6px;font-size:13px}.download{display:flex;justify-content:center;align-items:center;width:100%;padding:15px;border-radius:12px;background:#6a92ff;color:#071025;text-decoration:none;font-weight:800;margin:22px 0 14px}.download:hover{background:#85a7ff}.checksum code{display:block;margin-top:8px;color:#aab7cd;font-size:11px;overflow-wrap:anywhere}.note{font-size:12px;text-align:center;color:#657087}@media(max-width:560px){.card{padding:26px}.meta{grid-template-columns:1fr}}</style></head><body><main class="card"><div class="brand"><span class="shield">◆</span>Digitronics · Private Browser</div><h1>Download for Windows</h1><p>${notes}</p><span class="version">Version ${escapeHtml(release.version)}</span><div class="meta"><div><small>Build</small><strong>${release.build_number}</strong></div><div><small>Size</small><strong>${size}</strong></div><div><small>Commit</small><strong>${escapeHtml(commit)}</strong></div></div><a class="download" href="${escapeHtml(downloadUrl)}" rel="nofollow">Download Private Browser</a><div class="checksum"><small>SHA-256</small><code>${escapeHtml(release.sha256)}</code></div><p class="note">Private, time-limited download · Windows 10/11 x64</p></main></body></html>`;
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);
}
